### ISSUE TITLE
offline huggingface

### ISSUE THREAD

**Issue by Nuclear6** [myshell-ai/AIlice#18]
Because the region is restricted, I would like to ask how to load the model on hugging face offline?

<img width="1728" alt="image" src="https://github.com/myshell-ai/AIlice/assets/49468241/4a88757a-843b-4f7b-81c5-2bbe0745a1c2">

**Comment by stevenlu137** [comment]
1. You may try to download the model in GGUF format and use local inference services such as ollama/LM studio to solve this problem.

2. If you want to continue using the huggingface model, you can try this:
add the following configuration to config.json:

    "file": {
      "modelWrapper": "AModelLLAMA",
      "modelList": {
          "/path/to/model": {
		  "formatter": "...",
		  "contextWindow": ...,
		  "systemAsUser": false
        }}
    },

 and run it with the following command:

ailice_web --modelID=file:/path/to/model --prompt="main"

This method loads the model from a local path and theoretically does not require a network, but I am not sure if it still work properly under the new version of transformers.

**Comment by Nuclear6** [comment]
I moved to ubuntu and used micromamba to build an isolation environment. I encountered the following error: 

ModuleNotFoundError: No module named 'ailice.core.llm.AModelMistral'

**Comment by stevenlu137** [comment]
Sorry for that, I forgot to submit two newly created files.
Just get the latest  code on master branch and try again. Please let me know if you have any questions

**Comment by stevenlu137** [comment]
I forgot to remind you that the new version of the code needs to install new dependencies. If you are not reinstalling AIlice, just do this:
pip install mistralai anthropic

**Comment by Nuclear6** [comment]
not work, this is my config.json
<img width="1238" alt="image" src="https://github.com/myshell-ai/AIlice/assets/49468241/42adbc38-8dfd-4483-9ccd-f6bc6ba3e432">

ailice_main --modelID=file:/home/work/.cache/huggingface/hub/models--meta-llama--Llama-2-7b-chat-hf/snapshots/c1b0db933684edbfe29a06fa47eb19cc48025e93 --prompt="main"

<img width="1728" alt="image" src="https://github.com/myshell-ai/AIlice/assets/49468241/90298963-bdaa-4ca3-9e73-28bb8cc5dcb1">

**Comment by stevenlu137** [comment]
My mistake, I forgot that the latest AIlice uses a vector database implementation based on the transformers model. There is currently a temporary solution, modify config.json as follows:

  "services": {
    "storage": {
      "cmd": "python3 -m ailice.modules.AStorageChroma --addr=ipc:///tmp/AIliceStorage.ipc",
      "addr": "ipc:///tmp/AIliceStorage.ipc"
    },
    ....
  }

Note this is just a temporary solution, AStorageChroma.py will be removed in future. You may need to install chroma in your env.
