### ISSUE TITLE
Problems with ailice calling the model after installing it through lm studio

### ISSUE THREAD

**Issue by fatinghenji** [myshell-ai/AIlice#21]
```
(AIlice) PS G:\AIlice> ailice_main --modelID=lm-studio:Nexesenex/MIstral-QUantized-70b_Miqu-1-70b-iMat.GGUF --prompt="main" --contextWindowRatio=0.5
Encountered an exception, AIlice is exiting: 'lm-studio'
  File "G:\AIlice\ailice\AIliceMain.py", line 123, in main
    mainLoop(**kwargs)
  File "G:\AIlice\ailice\AIliceMain.py", line 38, in mainLoop
    config.Initialize(modelID = modelID)
  File "G:\AIlice\ailice\common\AConfig.py", line 125, in Initialize
    needAPIKey = ("apikey" in self.models[modelType] and (self.models[modelType]["apikey"] is None))
```

**Comment by stevenlu137** [comment]
It looks like this model is not pre-configured in config.json. Please refer to "How to Add LLM Support/Example 2: LM Studio". If you still encounter problems please let me know.

**Comment by fatinghenji** [comment]
> It looks like this model is not pre-configured in config.json. Please refer to "How to Add LLM Support/Example 2: LM Studio". If you still encounter problems please let me know.看起来这个模型没有在js.json中预先配置。请参考“如何添加LLM支持/示例2：LM Studio”。如果你仍然遇到问题，请让我知道。

[Where is config.json?](https://github.com/myshell-ai/AIlice/discussions/20)

**Comment by stevenlu137** [comment]
I updated the code of the master branch to let AIlice print out the location of config.json immediately when it starts. Please update the code and try to start AIlice.

**Comment by fatinghenji** [comment]
fix
