### ISSUE TITLE
Suggestion for claude

### ISSUE THREAD

**Issue by babybirdprd** [myshell-ai/AIlice#30]
Saw in your Readme that you haven't tried it with claude. Would recommend trying openrouter to try out claude. And maybe adding instructions for it. That way swapping models is just a matter of changing one line. Since they have openai compatibility. https://openrouter.ai/docs#quick-start

**Comment by stevenlu137** [comment]
Awesome tool! I've added full support in AIlice and updated the documentation. Thanks a lot for the information!
