### ISSUE TITLE
module storage failed

### ISSUE THREAD

**Issue by mostafaneq** [myshell-ai/AIlice#34]
PS C:\Users\ZIWIG\Downloads\ScraperAI\gpt4V-scraper\AIlice> ailice_web --modelID=groq:llama3-70b-8192
config.json is located at C:\Users\ZIWIG\AppData\Local\Steven Lu\ailice
In order to simplify installation and usage, we have set local execution as the default behavior, which means AI has complete control over the local environment. To prevent irreversible losses due to potential AI errors, you may consider one of the following two methods: the first one, run AIlice in a virtual machine; the second one, install Docker, use the provided Dockerfile to build an image and container, and modify the relevant configurations in config.json. For detailed instructions, please refer to the documentation.
storage  started.
browser  started.
arxiv  started.
google  started.
duckduckgo  started.
scripter  started.
computer  started.
Connecting module storage FAILED. You can try running the module manually and observe its error messages.
Connecting module storage FAILED. You can try running the module manually and observe its error messages.
Connecting module storage FAILED. You can try running the module manually and observe its error messages.
Connecting module storage FAILED. You can try running the module manually and observe its error messages.
Connecting module storage FAILED. You can try running the module manually and observe its error messages.
It seems that some peripheral module services failed to start. EXCEPTION: Resource temporarily unavailable
  File "C:\Users\ZIWIG\Downloads\ScraperAI\gpt4V-scraper\AIlice\ailice\AIliceWeb.py", line 47, in mainLoop
    clientPool.Init()
  File "C:\Users\ZIWIG\Downloads\ScraperAI\gpt4V-scraper\AIlice\ailice\common\ARemoteAccessors.py", line 17, in Init
    raise e
  File "C:\Users\ZIWIG\Downloads\ScraperAI\gpt4V-scraper\AIlice\ailice\common\ARemoteAccessors.py", line 14, in Init
    self.pool[cfg['addr']] = makeClient(cfg['addr'])
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZIWIG\Downloads\ScraperAI\gpt4V-scraper\AIlice\ailice\common\lightRPC.py", line 126, in makeClient
    ret=ReceiveMsg(socket)
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ZIWIG\Downloads\ScraperAI\gpt4V-scraper\AIlice\ailice\common\lightRPC.py", line 27, in ReceiveMsg
    return pickle.loads(conn.recv())
                        ^^^^^^^^^^^
  File "_zmq.py", line 1137, in zmq.backend.cython._zmq.Socket.recv
  File "_zmq.py", line 1172, in zmq.backend.cython._zmq.Socket.recv
  File "_zmq.py", line 1264, in zmq.backend.cython._zmq._recv_copy
  File "_zmq.py", line 1259, in zmq.backend.cython._zmq._recv_copy
  File "_zmq.py", line 152, in zmq.backend.cython._zmq._check_rc

**Comment by stevenlu137** [comment]
Could you please run the following command and provide me with the result? Thank you.

```bash
python3 -m ailice.modules.AStorageVecDB --addr=ipc:///tmp/AIliceStorage.ipc", "addr": "ipc:///tmp/AIliceStorage.ipc
```

**Comment by mostafaneq** [comment]
AIlice> python3 -m ailice.modules.AStorageVecDB --addr=ipc:///tmp/AIliceStorage.ipc", "addr": "ipc:///tmp/AIliceStorage.ipc
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by mostafaneq** [comment]
when i run the command , i get this error ,File "C:\Users\Downloads\ScraperAI\gpt4V-scraper\AIlice\ailice\modules\AStorageVecDB.py", line 3, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'  , even i installed torch using this pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 , and this also pip install torch

**Comment by stevenlu137** [comment]
That's strange. Did you install AIlice in a clean environment? Were there any errors during the installation of AIlice? 
Running AIlice on Windows requires WSL, and since I don't have a reliable Windows testing environment, the installation based directly on the Windows command line hasn't been thoroughly tested.

**Comment by lzylinl** [comment]
This happen if you run scripter in docker with ports 5900-59200 and try to run AIlice services on same ports. Just modify config.json with changed ports:
"services": {
    "storage": {
      "cmd": "python -m ailice.modules.AStorageVecDB --addr=tcp://127.0.0.1:58991",
      "addr": "tcp://127.0.0.1:58991"
    },
    "browser": {
      "cmd": "python -m ailice.modules.ABrowser --addr=tcp://127.0.0.1:58992",
      "addr": "tcp://127.0.0.1:58992"
    },
    "arxiv": {
      "cmd": "python -m ailice.modules.AArxiv --addr=tcp://127.0.0.1:58993",
      "addr": "tcp://127.0.0.1:58993"
    },
    "google": {
      "cmd": "python -m ailice.modules.AGoogle --addr=tcp://127.0.0.1:58994",
      "addr": "tcp://127.0.0.1:58994"
    },
    "duckduckgo": {
      "cmd": "python -m ailice.modules.ADuckDuckGo --addr=tcp://127.0.0.1:58995",
      "addr": "tcp://127.0.0.1:58995"
    },
    "scripter": {
      "cmd": "docker start scripter",
      "addr": "tcp://127.0.0.1:59000"
    },
    "speech": {
      "cmd": "python -m ailice.modules.ASpeech --addr=tcp://127.0.0.1:58996",
      "addr": "tcp://127.0.0.1:58996"
    },
    "computer": {
      "cmd": "python -m ailice.modules.AComputer --addr=tcp://127.0.0.1:58997",
      "addr": "tcp://127.0.0.1:58997"
    }
  }
