### ISSUE TITLE
Agent often assumes wrong OS

### ISSUE THREAD

**Issue by FellowTraveler** [myshell-ai/AIlice#42]
I'm using MacOS and sometimes I see the agent trying to **"sudo apt-get install..."**
When I notice that, it reminds me to add **"You are on MacOS so don't use any linux-specific bash commands"** to the prompt when I re-try.
Is this not already in the system prompt?
I will dig into the code but would also like to do a short call if possible to speed me up.

**Comment by stevenlu137** [comment]
Yes, AIlice currently does not provide prompts for different operating systems. 

I developed AIlice based on Linux and lack development environments for Windows and Mac, which has led to various issues on those platforms. We need a more powerful command-line execution function to replace the current BASH, and we need to automatically detect the system environment and prompt the agents about the current environment to avoid the issues you mentioned.

**Comment by stevenlu137** [comment]
Agents can automatically see information related to the code execution environment in the latest version on the dev branch now.
