### ISSUE TITLE
openai.APIConnectionError: Connection error using qwen2-72b

### ISSUE THREAD

**Issue by jechaviz** [myshell-ai/AIlice#55]
Everthing looks good at the start:
![image](https://github.com/user-attachments/assets/d89baaa1-fbb0-4f57-bbce-9204ad85f0b3)
This is my relevant screenshot of my configuration file:
![image](https://github.com/user-attachments/assets/891b010b-3240-4ae8-9c61-5e62e333769d)
It runs ok in browser:
![image](https://github.com/user-attachments/assets/7c1798c3-185b-48bf-8393-cf0bcb84a06d)
As soon as i wrote "Hi" it happened in console:
![image](https://github.com/user-attachments/assets/5023e50f-2ec6-4780-9c51-0736a58648da)
![image](https://github.com/user-attachments/assets/7b2c5b47-dd03-4f04-a274-3c911973f879)
![image](https://github.com/user-attachments/assets/96dc5792-5c75-4cb6-9ddf-26d29135ac1d)
I'm only using qwen, not api of openai.
Finally I see this error: 
`openai.APIConnectionError: Connection error.`
I downloaded this from LMStudio:
`qwen2-72b-instruct-q4_k_m.gguf
https://huggingface.co/Qwen/Qwen2-72B-Instruct-GGUF/resolve/main/qwen2-72b-instruct-q4_k_m.gguf
`

**Comment by stevenlu137** [comment]
I didn’t see any issues in the image. LMStudio provides an OpenAI-compatible API, so we use OpenAI’s API library to access the LMStudio service. However, for some reason, the connection failed, causing the issue shown in the image. This is usually because LMStudio didn’t start the model, or a different address and port were used. Could you introduce your LMStudio setup?

**Comment by jechaviz** [comment]
You were right, I missed to start server in lm-studio
Now it doesn't appear to have any issue.
![image](https://github.com/user-attachments/assets/26e97e14-1208-489f-a57c-a4ae15b984bc)

But, it's like really slow. How much RAM/CPU I must have?
I've 8 cores 20GB RAM at this moment.
![image](https://github.com/user-attachments/assets/7199709b-bb7b-480d-9070-a3641705d2dc)

**Comment by stevenlu137** [comment]
I usually run Q3_K_S on dual 4090s (48GB VRAM), and the VRAM size is just enough for a 16k context window. In comparison, it’s not surprising that running a larger Q4_K_M on 20GB RAM failed. Also, CPU inference is indeed much slower than GPU. I don’t know the exact speed, but it’s likely slow enough to make AIlice’s execution speed unacceptable. 

You can look for or wait for more efficient inference frameworks to emerge, install a GPU with more VRAM, or more simply, use openrouter or OpenAI’s newly launched gpt-4o-mini, which is affordable and has good performance.
